services:
  - type: web
    name: hio-app
    env: java
    plan: starter
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/HIO-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: your_database_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: CLIENT_URL
        value: https://your-frontend-url.com
      - key: PORT
        value: "10000" # если нужен кастомный порт
