services:
  - type: web
    name: hio-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromService:
          name: hio-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          name: hio-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          name: hio-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: 8080

  - type: web
    name: hio-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free

  - type: postgres
    name: hio
